;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Object",DevComment="Default Object in the world")
+GameplayTagList=(Tag="Object.Item",DevComment="Something That can be place In ad Inventory")
+GameplayTagList=(Tag="Object.Item.Consumable",DevComment="")
+GameplayTagList=(Tag="Object.Item.Consumable.Sandwhich",DevComment="")
+GameplayTagList=(Tag="Object.Item.QuestItem",DevComment="")
+GameplayTagList=(Tag="Object.Item.Resource",DevComment="")
+GameplayTagList=(Tag="Object.Item.Resource.Stone",DevComment="")
+GameplayTagList=(Tag="Object.Item.Resource.Wood",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Melee",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range.Bow",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range.Crossbow",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range.Gun",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range.Gun.Pistol",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range.Gun.Rifle",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range.Gun.Rifle.Winchester308",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range.Gun.Shotgun",DevComment="")
+GameplayTagList=(Tag="Object.Item.Weapon.Range.Thrown",DevComment="")
+GameplayTagList=(Tag="PPC",DevComment="Possesible Character")
+GameplayTagList=(Tag="PPC.Animal",DevComment="")
+GameplayTagList=(Tag="PPC.Animal.Birds",DevComment="")
+GameplayTagList=(Tag="PPC.Animal.Fish",DevComment="")
+GameplayTagList=(Tag="PPC.Animal.Mammal",DevComment="")
+GameplayTagList=(Tag="PPC.Animal.Mammal.Antelope",DevComment="")
+GameplayTagList=(Tag="PPC.Animal.Repitle",DevComment="")
+GameplayTagList=(Tag="PPC.Humanoid",DevComment="")
+GameplayTagList=(Tag="PPC.Humanoid.Elf",DevComment="")
+GameplayTagList=(Tag="PPC.Humanoid.HalfElf",DevComment="")
+GameplayTagList=(Tag="PPC.Humanoid.Human",DevComment="")
+GameplayTagList=(Tag="PPC.Humanoid.Orc",DevComment="")
+GameplayTagList=(Tag="PPC.State",DevComment="")
+GameplayTagList=(Tag="PPC.State.Awake",DevComment="")
+GameplayTagList=(Tag="PPC.State.Dormant",DevComment="Meant to suggest Metabloic state is inactive player update tick is off")

